
float3 main(float3 frontColor: COLOR0,
			float2 texCoord0: TEXCOORD0,
			float2 texCoord1: TEXCOORD1,
			sampler2D tex0: TEXUNIT0,
			uniform float time,
			uniform float2 plasmaCoord): COLOR
{
    float2 tc= texCoord1*5+plasmaCoord;
	float a= sin(sin(time)+tc.y)*tc.y+tc.x;
	float value= a*sin(time+tc.x);
	float3 m= frontColor - float3(tc.x, tc.y, -tc.x)*.25;
	return float3( sin(value*.7+time) * m + m ) + tex2D(tex0, texCoord0);
}



